# Generated by Django 5.1 on 2024-09-03 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular author across whole library', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Enter author's name", max_length=255)),
                ('bio', models.TextField(help_text="Enter author's bio")),
                ('birth_date', models.DateField(help_text="Enter author's birth date")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Enter book's title", max_length=255)),
                ('description', models.TextField(help_text="Enter book's description")),
                ('publish_date', models.DateField(help_text="Enter book's publish date")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
