# Generated by Django 5.1 on 2024-09-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text="Enter book's author", on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author'),
        ),
    ]
